In [1]:
from dataclasses import field
import ratelimit
import time
import gspread
from ratelimit import limits
%matplotlib ipympl
import ipywidgets as widgets
from utilities import find_latest_file, setup_logging, cleanup_str, get_gs_config
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.widgets as wg
import geopandas as gpd
import folium
import collectDataFromSheets
import os
log = setup_logging("JUP LOG")

In [2]:
df = find_latest_file("Full")
gdf = gpd.GeoDataFrame(df, crs="EPSG:4326", geometry=gpd.points_from_xy(x=df["Longitude"], y=df["Latitude"]))

In [3]:
# gdf.explore(markers="v", column="Year", )

In [4]:
gdf = gpd.read_file("pdf.geojson")
gdf.set_crs(epsg=4326, inplace=True, allow_override=True)
m = gdf.explore(fill=False, name="County Outlines", legend=True, )
folium.LayerControl().add_to(m)

"

In [5]:
def get_widget_data(year_range_slider, apple_names_p_drops, min_fair_threshold_dropdown):
    year_max = year_range_slider.value[1]
    year_min = year_range_slider.value[0]
    apple_names = []
    if not check_rand:
        for apple_dropdown in apple_names_p_drops:
            apple_names.append(apple_dropdown.value)
    else:
        apple_names = apple_names_p_drops

    df = find_latest_file("Full")

    df = df.merge(df.groupby("Year")["Event"].count().rename("Number of Events in a Year"), how="left", on="Year")

    df = df.loc[df["Number of Events in a Year"] >= min_fair_threshold_dropdown.value]

    if len(apple_names) > 0:
        df = df.loc[df["Use Name"].isin(apple_names)]

    nf = df.loc[df["Year"] <= year_max]
    nf = nf.loc[nf['Year'] >= year_min]

    if check_rand.value:
        nf = nf.loc[df["Use Name"].isin(nf.groupby("Use Name")["Year"].count().sort_values(ascending=False).head(number_of_apples.value).reset_index()["Use Name"])]

    for apple_name in apple_names:
        nf = nf.merge(nf.loc[nf["Use Name"] == apple_name].groupby("Year")["Event"].count().rename(f"# {apple_name} fair"), how="left", on="Year")
        nf[f"% in fairs"] = nf[f"# {apple_name} fair"] / nf["Number of Events in a Year"] * 100
    gdf = gpd.GeoDataFrame(nf, crs="EPSG:4326", geometry=gpd.points_from_xy(x=nf["Longitude"], y=nf["Latitude"]))
    return gdf

In [6]:
df = find_latest_file("Full")
year_slider = widgets.IntRangeSlider(min=df['Year'].min(), max=df['Year'].max(), value=[df['Year'].min(), df['Year'].max()])
number_of_apples = widgets.IntText(min=0, max=len(df["Use Name"].unique()), value=2, description="Number of apples")
min_fair_threshold = widgets.IntText(min=0, value=10, description="Fair Threshold")
check_rand = widgets.Checkbox(description="random", value=True)
display(year_slider, number_of_apples, min_fair_threshold, check_rand)

IntRangeSlider(value=(1838, 1957), max=1957, min=1838)

IntText(value=2, description='Number of apples')

IntText(value=10, description='Fair Threshold')

Checkbox(value=True, description='random')

In [7]:
def get_most_common_apples():
    nf = find_latest_file("Full")
    return nf.groupby("Use Name")["Year"].count().sort_values(ascending=False).head(number_of_apples.value).reset_index()["Use Name"]

In [74]:
apples_dropdowns = []
if not check_rand.value:
    for i in range(number_of_apples.value):
        apples_dropdowns.append(widgets.Dropdown(options=df["Use Name"].unique(), value="baldwin", description=f"Select Apple Type[{i + 1}]"))
    for dropdown in apples_dropdowns:
       display(dropdown)
else:
    apples_dropdowns = get_most_common_apples()

In [75]:
nf = get_widget_data(year_slider, apples_dropdowns, min_fair_threshold)
nf

,County,Event,Year,IsApple,Given Name,Given Name Clean,Old Alt Name,Old Presumed Name,Use Name,Possibly Wrong Use Name,...,# (pear) howell fair,# nonesuch fair,# president fair,# fletcher sweet fair,# opalescent fair,# wine fair,# hyslop crab fair,# orange sweet fair,# winter sweet fair,geometry
0,androscoggin,androscoggin county,1906,True,Baldwin,baldwin,NaN,Baldwin,baldwin,NaN,...,NaN,1.0,1.0,1.0,NaN,NaN,4.0,1.0,NaN,POINT (-70.17474 44.47467)
1,androscoggin,androscoggin county,1906,True,Ben Davis,ben davis,NaN,Ben Davis,ben davis,NaN,...,NaN,1.0,1.0,1.0,NaN,NaN,4.0,1.0,NaN,POINT (-70.17474 44.47467)
2,androscoggin,androscoggin county,1906,True,Duchess of Oldenburg,duchess of oldenburg,NaN,Duchess of Oldenberg,duchess of oldenburg,NaN,...,NaN,1.0,1.0,1.0,NaN,NaN,4.0,1.0,NaN,POINT (-70.17474 44.47467)
3,androscoggin,androscoggin county,1906,True,Harvey Greening,harvey greening,Harvey,NaN,fall harvey,NaN,...,NaN,1.0,1.0,1.0,NaN,NaN,4.0,1.0,NaN,POINT (-70.17474 44.47467)
4,androscoggin,androscoggin county,1906,True,Fall Jenneting,fall jenneting,NaN,Fall Jenneting,fall jenneting,NaN,...,NaN,1.0,1.0,1.0,NaN,NaN,4.0,1.0,NaN,POINT (-70.17474 44.47467)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11834,york,york county farm bureau meeting,1925,True,Gravenstein,gravenstein,NaN,NaN,gravenstein,NaN,...,2.0,NaN,NaN,1.0,3.0,NaN,1.0,1.0,NaN,POINT (-70.77642 43.44334)
11835,york,york county farm bureau meeting,1925,True,McIntosh Red,mcintosh red,NaN,NaN,mcintosh,NaN,...,2.0,NaN,NaN,1.0,3.0,NaN,1.0,1.0,NaN,POINT (-70.77642 43.44334)
11836,york,york county farm bureau meeting,1925,True,Northern Spy,northern spy,NaN,NaN,northern spy,NaN,...,2.0,NaN,NaN,1.0,3.0,NaN,1.0,1.0,NaN,POINT (-70.77642 43.44334)
11837,york,york county farm bureau meeting,1925,True,Delicious,delicious,NaN,NaN,red delicious,NaN,...,2.0,NaN,NaN,1.0,3.0,NaN,1.0,1.0,NaN,POINT (-70.77642 43.44334)
11838,york,york county farm bureau meeting,1925,True,Wealthy,wealthy,NaN,NaN,wealthy,NaN,...,2.0,NaN,NaN,1.0,3.0,NaN,1.0,1.0,NaN,POINT (-70.77642 43.44334)

In [1]:
plt.cla()
# sns.displot(nf, x="Year", kind="hist", kde=True, col="Use Name", col_wrap=5, hue="Use Name")

NameError: name 'plt' is not defined

In [78]:
find_latest_file("Apples")

,County,Event,Year,IsApple,Given Name,Given Name Clean,Old Alt Name,Alt Name Clean,Old Presumed Name,Presumed Name Clean
0,androscoggin,androscoggin county,1875,False,(Pear) Bartlett,(pear) bartlett,NaN,NaN,(Pear) Bartlett,(pear) bartlett
1,androscoggin,androscoggin county,1875,False,(Pear) Beurre d'Anjou,(pear) beurre d'anjou,NaN,NaN,(Pear) Beurre d'Anjou,(pear) beurre d'anjou
2,androscoggin,androscoggin county,1875,False,(Pear) Elizabeth,(pear) elizabeth,NaN,NaN,(Pear) Elizabeth,(pear) elizabeth
3,androscoggin,androscoggin county,1875,False,(Pear) Napoleon,(pear) napoleon,NaN,NaN,(Pear) Napoleon,(pear) napoleon
4,androscoggin,androscoggin county,1875,False,(Pear) Seckel,(pear) seckel,NaN,NaN,(Pear) Seckel,(pear) seckel
...,...,...,...,...,...,...,...,...,...,...
27275,york,york county farm bureau meeting,1925,True,Delicious,delicious,NaN,NaN,NaN,NaN
27276,york,york county farm bureau meeting,1925,True,Gravenstein,gravenstein,NaN,NaN,NaN,NaN
27277,york,york county farm bureau meeting,1925,True,McIntosh Red,mcintosh red,NaN,NaN,NaN,NaN
27278,york,york county farm bureau meeting,1925,True,Northern Spy,northern spy,NaN,NaN,NaN,NaN
27279,york,york county farm bureau meeting,1925,True,Wealthy,wealthy,NaN,NaN,NaN,NaN

In [80]:
pd.read_csv("cleanedData/Apples/apples_2025-08-23-15:55.csv")

,County,Event,Year,IsApple,Given Name,Given Name Clean,Old Alt Name,Alt Name Clean,Old Presumed Name,Presumed Name Clean
0,knox,knox county,1867,True,Pearmain,pearmain,NaN,NaN,NaN,NaN
1,knox,knox county,1867,True,Porter,porter,NaN,NaN,Porter,porter
2,knox,knox county,1869,False,(Pear) Flemish Beauty,(pear) flemish beauty,NaN,NaN,NaN,NaN
3,knox,knox county,1869,True,Baldwin,baldwin,NaN,NaN,Baldwin,baldwin
4,knox,knox county,1869,True,Fall Pippin,fall pippin,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
27275,lincoln,nobleboro grange,1921,True,Sweet Russet,sweet russet,NaN,NaN,NaN,NaN
27276,lincoln,nobleboro grange,1921,True,Tolman sweet,tolman sweet,NaN,NaN,NaN,NaN
27277,lincoln,nobleboro grange,1921,True,Wealthy,wealthy,NaN,NaN,NaN,NaN
27278,lincoln,nobleboro grange,1921,True,Wolf River,wolf river,NaN,NaN,NaN,NaN
27279,lincoln,nobleboro grange,1921,True,York Imperial,york imperial,NaN,NaN,NaN,NaN

In [4]:
apples = find_latest_file("Full")
apples

,County,Event,Year,IsApple,Given Name,Given Name Clean,Old Alt Name,Old Presumed Name,Use Name,Possibly Wrong Use Name,...,Alt Names,Alt Given Names,Location,Additional Notes,Source: 1,Source: 2,Source: 3,Source: 4,Latitude,Longitude
0,androscoggin,androscoggin county,1875,False,(Pear) Bartlett,(pear) bartlett,NaN,(Pear) Bartlett,(pear) bartlett,NaN,...,(pear) williams bon chretien,(pear) barltett|(pear) bartlett,NaN,NaN,lewiston evening journal|1875-10-06 00:00:00||...,lewiston evening journal|1875-10-07 00:00:00||...,NaN,NaN,44.18700,-70.198000
1,androscoggin,androscoggin county,1875,False,(Pear) Beurre d'Anjou,(pear) beurre d'anjou,NaN,(Pear) Beurre d'Anjou,(pear) beurre d'anjou,NaN,...,(pear) beaurree d'anjou|(pear) benne d'anjou|(...,(pear) anglo|(pear) anjon|(pear) anjou|(pear) ...,NaN,NaN,lewiston evening journal|1875-10-06 00:00:00||...,lewiston evening journal|1875-10-07 00:00:00||...,NaN,NaN,44.18700,-70.198000
2,androscoggin,androscoggin county,1875,False,(Pear) Elizabeth,(pear) elizabeth,NaN,(Pear) Elizabeth,(pear) elizabeth,NaN,...,NaN,(pear) elizabeth|(pear) manings elizabeth,NaN,NaN,lewiston evening journal|1875-10-06 00:00:00||...,lewiston evening journal|1875-10-07 00:00:00||...,NaN,NaN,44.18700,-70.198000
3,androscoggin,androscoggin county,1875,False,(Pear) Napoleon,(pear) napoleon,NaN,(Pear) Napoleon,(pear) napoleon,NaN,...,NaN,(pear) napolean|(pear) napoleon,NaN,NaN,lewiston evening journal|1875-10-06 00:00:00||...,lewiston evening journal|1875-10-07 00:00:00||...,NaN,NaN,44.18700,-70.198000
4,androscoggin,androscoggin county,1875,False,(Pear) Seckel,(pear) seckel,NaN,(Pear) Seckel,(pear) seckel,NaN,...,"(pear) sickel|(pear) sickel, sickle|(pear) sic...",(pear) seckel|(pear) sekel|(pear) shekal|(pear...,NaN,NaN,lewiston evening journal|1875-10-06 00:00:00||...,lewiston evening journal|1875-10-07 00:00:00||...,NaN,NaN,44.18700,-70.198000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27243,york,york county farm bureau meeting,1925,True,Gravenstein,gravenstein,NaN,NaN,gravenstein,NaN,...,gravenstine|gravinstein|grovenstein,fall gravenstein|graveline|gravenstein|gravens...,sanford,NaN,biddeford weekly journal|1925-11-06 00:00:00|p...,NaN,NaN,NaN,43.44334,-70.776419
27244,york,york county farm bureau meeting,1925,True,McIntosh Red,mcintosh red,NaN,NaN,mcintosh,NaN,...,machintosh red|macintosh red|mackintosh|mackin...,macintosh|macintosh red|mackintosh|mackintosh ...,sanford,NaN,biddeford weekly journal|1925-11-06 00:00:00|p...,NaN,NaN,NaN,43.44334,-70.776419
27245,york,york county farm bureau meeting,1925,True,Northern Spy,northern spy,NaN,NaN,northern spy,NaN,...,spy,n. spy|n. y. spy|nathan spy|no. spy|northern s...,sanford,NaN,biddeford weekly journal|1925-11-06 00:00:00|p...,NaN,NaN,NaN,43.44334,-70.776419
27246,york,york county farm bureau meeting,1925,True,Delicious,delicious,NaN,NaN,red delicious,NaN,...,red delicious,delicious|red delicious,sanford,NaN,biddeford weekly journal|1925-11-06 00:00:00|p...,NaN,NaN,NaN,43.44334,-70.776419
27247,york,york county farm bureau meeting,1925,True,Wealthy,wealthy,NaN,NaN,wealthy,NaN,...,NaN,meallhy|wealthty|wealthy|wheatley|worthley,sanford,NaN,biddeford weekly journal|1925-11-06 00:00:00|p...,NaN,NaN,NaN,43.44334,-70.776419

In [99]:
def get_town_coordinates() -> pd.DataFrame:
    coords = Spread("TownCoordinatesTest", config=get_gs_config())
    coords = coords.sheet_to_df()
    coords = coords.sort_index().reset_index()
    coords["Latitude"] = coords["Latitude"].apply(lambda x: np.float64(x))
    coords["Longitude"] = coords["Longitude"].apply(lambda x: np.float64(x))
    coords["Location"] = coords["Location"].apply(lambda x: x.strip())
    return coords
def get_county_coordinates() -> pd.DataFrame:
    coords = Spread("CountyCoordinatesTest", config=get_gs_config())
    coords = coords.sheet_to_df()
    coords = coords.sort_index().reset_index()
    coords["Latitude"] = coords["Latitude"].apply(lambda x: np.float64(x))
    coords["Longitude"] = coords["Longitude"].apply(lambda x: np.float64(x))
    coords["County"] = coords["County"].apply(lambda x: x.strip())
    return coords
def get_name_key() -> pd.DataFrame:
    coords = Spread("NameKeyTest", config=get_gs_config())
    # coords = coords.sheet_to_df()
    # coords = coords.sort_index().reset_index()
    # coords["IsApple"] = coords["IsApple"].apply(lambda x: True if x == "TRUE" else False)
    return coords
c = get_name_key()
c

In [96]:
pd.read_csv("sourceKeys/NameKey.csv")

,IsApple,Given Name Clean,Presumed Name Clean,Use Name,Possibly Wrong Use Name
0,True,abe lincoln,red astrachan,red astrachan,NaN
1,True,acme,acme,acme,NaN
2,False,(pear) adelaide,(pear) adalaine,(pear) adalaine,NaN
3,False,(pear) adeline,(pear) adalaine,(pear) adalaine,NaN
4,True,alexander,alexander,alexander,NaN
...,...,...,...,...,...
2252,True,york russett,NaN,york russet,NaN
2253,True,york sweet,NaN,york sweet,NaN
2254,True,york sweeting,NaN,york sweet,NaN
2255,True,zeal apple,NaN,zeal apple,NaN
2256,True,zylphia,NaN,zyplhia,NaN

In [90]:
d = c.merge(coords, how="outer", indicator=True)
d

       Location   Latitude  Longitude _merge
0         acton  43.523400 -70.927800   both
1        alfred  43.475116 -70.715284   both
2       amherst  44.832300 -68.364000   both
3       andover  44.635953 -70.751691   both
4         anson  44.827771 -69.942668   both
..          ...        ...        ...    ...
196     windsor  44.311261 -69.581346   both
197     winslow  44.552195 -69.602983   both
198  winterport  44.644572 -68.860274   both
199    winthrop  44.307550 -69.974289   both
200    woolwich  43.918705 -69.800957   both

[201 rows x 4 columns]

In [86]:
cols = c.columns
d["same lat"] = d["Latitude_y"].isin(d["Latitude_x"])
d

       Location  Latitude_x  Longitude_x  Latitude_y  Longitude_y  same lat
0         acton   43.523400   -70.927800   43.523400   -70.927800      True
1        alfred   43.475116   -70.715284   43.475116   -70.715284      True
2       amherst   44.832300   -68.364000   44.832300   -68.364000      True
3       andover   44.635953   -70.751691   44.635953   -70.751691      True
4         anson   44.827771   -69.942668   44.827771   -69.942668      True
..          ...         ...          ...         ...          ...       ...
189     windsor   44.311261   -69.581346   44.311261   -69.581346      True
190     winslow   44.552195   -69.602983   44.552195   -69.602983      True
191  winterport   44.644572   -68.860274   44.644572   -68.860274      True
192    winthrop   44.307550   -69.974289   44.307550   -69.974289      True
193    woolwich   43.918705   -69.800957   43.918705   -69.800957      True

[194 rows x 6 columns]

        Location   Latitude  Longitude             type
0          acton  43.523400 -70.927800  <class 'float'>
1         alfred  43.475116 -70.715284  <class 'float'>
2        amherst  44.832300 -68.364000  <class 'float'>
3        andover  44.635953 -70.751691  <class 'float'>
4          anson  44.827771 -69.942668  <class 'float'>
..           ...        ...        ...              ...
189       norway  44.214344 -70.544771  <class 'float'>
190  east sumner  44.356849 -70.376964  <class 'float'>
191   welchville  44.133728 -70.463796  <class 'float'>
192       calais  45.140243 -67.230747  <class 'float'>
193       dayton  43.537564 -70.575460  <class 'float'>

[194 rows x 4 columns]

In [128]:
gc = gspread.oauth(credentials_filename="Secrets/JackClientIDs.json")

In [133]:
apple_folder_id = "1Clo7Sax3tSzm_xJGiVc4E2jMNDONaR8F"
apple_file_info = gc.list_spreadsheet_files(folder_id=apple_folder_id)

TypeError: list indices must be integers or slices, not str

In [149]:
class Spread:
    def __init__(self, info, google_client, folder_id):
        self.id = info["id"]
        self.name = info["name"]
        self.spreadsheet = google_client.open(self.name, folder_id=folder_id)
        self.worksheets_info = self.spreadsheet.worksheets()
        self.worksheets = [WorkSheet(self.spreadsheet, info) for info in self.worksheets_info]
class WorkSheet:
    def __init__(self, spreadsheet, worksheet_info):
        self.name = worksheet_info.title
        self.id = worksheet_info.id
        self.df = self.sheet_to_df()
    @limits(calls=300, period=60)
    def sheet_to_df(self):
         return pd.DataFrame(spreadsheet.worksheet(self.name).get_all_records(), index=None)

In [148]:
start_time = time.time()
spreads = []
for n in apple_file_info:
    print(n["name"])
    spreads.append(Spread(n, gc, apple_folder_id))
    print(time.time() - start_time)

Copy of Copy of Maine, Androscoggin County Fairs
15.1146879196167
Copy of Copy of Maine, Kennebec County Fairs

WorksheetNotFound: Chelsea Grange

In [4]:
raw_data = collectDataFromSheets._collect_data_from_google()

credentials loaded 0.0031218528747558594
services loaded 0.009227752685546875
done with Copy of Copy of Maine, Knox County Fairs !!! 3.1754817962646484
done with Copy of Copy of Maine, Androscoggin County Fairs !!! 1.8428893089294434
done with Copy of Copy of Maine, Kennebec County Fairs !!! 2.973876953125
done with Copy of Copy of Maine, Cumberland County Fairs !!! 2.3062069416046143
done with Copy of Copy of Maine, Hancock County Fairs !!! 1.9981589317321777
done with Copy of Copy of Maine, Franklin County Fairs !!! 2.2472879886627197
done with Copy of Copy of Maine, Aroostook County Fairs !!! 3.0687921047210693
done with Copy of Copy of Maine, Penobscot County Fairs !!! 2.833872079849243
done with Copy of Copy of Maine, Piscataquis County Fairs !!! 1.7748711109161377
done with Copy of Copy of Maine, Oxford County Fairs !!! 2.1660821437835693
done with Copy of Copy of Maine, Lincoln County Fairs !!! 1.5712361335754395
done with Copy of Copy of Maine, Sagadahoc County Fairs !!! 1.3019979000091553
done with Copy of Copy of Maine, Washington County Fairs !!! 1.406477928161621
done with Copy of Copy of Maine, Waldo County Fairs !!! 2.7671427726745605
done with Copy of Copy of Maine, Somerset County Fairs !!! 2.1499080657958984
done with Copy of Copy of Maine, York County Fairs !!! 1.9465010166168213

dropped none columns: Index([None], dtype='object', name=0)
dropped none columns: Index([None], dtype='object', name=0)
dropped none columns: Index([None, None, None, None, None, None, None, None, None, None,
       ...
       None, None, None, None, None, None, None, None, None, None],
      dtype='object', name=0, length=949)
dropped none columns: Index([None], dtype='object', name=0)

,,1838,1842,1847,1848,1849,1850,1851,1852,1853,...,Som. Cen.,Som. Co. Farm. Bur.,Starks,Total,Variety,W. Athens,W. B. & S. B.,Wellington,county name,event name
1,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,(Pear) Bartlett,NaN,NaN,NaN,androscoggin,varieties list
2,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,(Pear) Belle Lucrative,NaN,NaN,NaN,androscoggin,varieties list
3,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,(Pear) Beurre d'Anjou,NaN,NaN,NaN,androscoggin,varieties list
4,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,(Pear) Buffum,NaN,NaN,NaN,androscoggin,varieties list
5,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,(Pear) Clapps Favorite,NaN,NaN,NaN,androscoggin,varieties list
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Wolf River,NaN,NaN,NaN,york,varieties list
240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Woodpecker,NaN,NaN,NaN,york,varieties list
241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Yellow Bellflower,NaN,NaN,NaN,york,varieties list
242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,York Imperial,NaN,NaN,NaN,york,varieties list
243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,York Russeting,NaN,NaN,NaN,york,varieties list

In [3]:

    df.columns

NameError: name 'raw_data' is not defined

In [15]:
spreads

NameError: name 'spreads' is not defined